sudo: required
services:
 - docker

before_install:
 - docker build -t before_travis -f Dockerfile.dev .

script:
 - docker run -e CI=true before_travis npm run test


deploy:
 provider: elasticbeanstalk
 region: "us-east-2"
 app: "docker-react-aws"
 env: "DockerReactAws-env"
 bucket_name: "elasticbeanstalk-us-east-2-314211910001"
 bucket_path: "docker-react-aws"
 on:
  branch: master
 access_key_id: "$AWS_ACCESS_KEY"
 secret_access_key: "$AWS_SECRET_KEY"

